name: vakharia_forex
description: "VakhariaForex - Forex Trading Commission Tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  csv: ^6.0.0
  pdf: ^3.10.8
  printing: ^5.14.2
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 